GO
CREATE SCHEMA [DB_ORDER_MANAGEMENT_SQL]

/* Create Account table */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DB_ORDER_MANAGEMENT_SQL].[Account] (
	[Id] [uniqueidentifier] DEFAULT NEWID() NOT NULL,
	[UserName] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/* Create Employee table */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DB_ORDER_MANAGEMENT_SQL].[Employee] (
	[Id] [uniqueidentifier] DEFAULT NEWID() NOT NULL,
	[Name] [nvarchar](50) NULL,
	[PhoneNumber] [varchar](50) NULL,
	CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/* Create Order table */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DB_ORDER_MANAGEMENT_SQL].[Order] (
	[Id] [uniqueidentifier] DEFAULT NEWID() NOT NULL,
	[CustomerName] [nvarchar](50) NULL,
	[PhoneNumber] [varchar](50) NULL,
	[Address] [nvarchar](250) NULL,
	[JobTitle] [nvarchar](50) NULL,
	[JobDescription] [nvarchar](MAX) NULL,
	[Status] [nvarchar](250) NOT NULL,
	[Signature] [nvarchar](MAX) NULL,
	[EmployeeId] [uniqueidentifier] NOT NULL
	CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/* Create OrderLog table */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
CREATE TABLE [DB_ORDER_MANAGEMENT_SQL].[OrderLog] (
	[Id] [uniqueidentifier] DEFAULT NEWID() NOT NULL,
	[Content] [nvarchar](MAX) NOT NULL,
	[CreateBy] [nvarchar] (250) NOT NULL,
	[CreatedOn] [date] NOT NULL,
	[OrderId] [uniqueidentifier] NOT NULL
	CONSTRAINT [PK_OrderLog] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [DB_ORDER_MANAGEMENT_SQL].[Order]  WITH CHECK ADD  CONSTRAINT [PK_Order_Employee] FOREIGN KEY([EmployeeId])
REFERENCES [DB_ORDER_MANAGEMENT_SQL].[Employee] ([Id])
GO
ALTER TABLE [DB_ORDER_MANAGEMENT_SQL].[Order] CHECK CONSTRAINT [PK_Order_Employee]
GO
ALTER TABLE [DB_ORDER_MANAGEMENT_SQL].[OrderLog]  WITH CHECK ADD  CONSTRAINT [PK_OrderLog_Order] FOREIGN KEY([OrderId])
REFERENCES [DB_ORDER_MANAGEMENT_SQL].[Order] ([Id])
GO
ALTER TABLE [DB_ORDER_MANAGEMENT_SQL].[OrderLog] CHECK CONSTRAINT [PK_OrderLog_Order]
